name: Auto Assign Reviewers for Main PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Request reviewers if base is main
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const baseRef = context.payload.pull_request.base.ref;

            // Добавляем ревьюеров только если PR вливается в main
            if (baseRef === 'main') {
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: prNumber,
                reviewers: ['Ruv1c0n', 'Soulnier'],
                team_reviewers: []
              });
            }
